<#
.SYNOPSIS
    One-file installer for the GitHub Copilot CLI Launcher kit.
    Wizard mode (default): prompts for project name, install location, etc.,
    writes all kit files, and creates a Windows desktop shortcut.
    Silent mode: pass parameters to skip prompts.

.DESCRIPTION
    This is a self-contained installer. It embeds the entire kit
    (Launch-Copilot.ps1, repair-copilot-sessions.py, AGENTS.md template,
    config schema) as base64-encoded payloads. No external downloads or
    git clone required.

    Generated by: tools/copilot-launcher/build-installer.ps1
    Source repo:  {{REPO_URL}}
    Build date:   {{BUILD_DATE}}

.PARAMETER InstallDir
    Where to install the kit. Default: %USERPROFILE%\copilot-launcher

.PARAMETER ProjectName
    Used in messages and as the default briefing-session name.
    Default: prompted (or current dir name in silent mode).

.PARAMETER StateDir
    Where briefing logs and state files live.
    Default: %USERPROFILE%\Desktop\CopilotCLI\<ProjectName>

.PARAMETER ResumeSession
    Copilot CLI session name to --resume on launch (e.g. "MyProject-Main").
    Leave empty to start a fresh session each launch. Default: empty.

.PARAMETER EnableAISummary
    Add -AISummary to the shortcut. Costs one premium request per launch
    when an update is detected. Default: prompted.

.PARAMETER EnableAllowAll
    Add --allow-all to the shortcut (Copilot CLI auto-approve mode).
    Default: prompted.

.PARAMETER NoDesktopShortcut
    Skip creating the desktop shortcut. Default: shortcut is created
    (after a wizard confirmation prompt).

.PARAMETER Silent
    Skip all prompts and use parameter values + defaults.

.EXAMPLE
    # Interactive wizard
    .\Install-CopilotLauncher.ps1

.EXAMPLE
    # Silent install with defaults
    .\Install-CopilotLauncher.ps1 -Silent -ProjectName "MyApp" -ResumeSession "MyApp-Main" -EnableAISummary -EnableAllowAll

.EXAMPLE
    # Custom install dir, no shortcut
    .\Install-CopilotLauncher.ps1 -InstallDir "D:\tools\copilot-launcher" -NoDesktopShortcut
#>
[CmdletBinding()]
param(
    [string]$InstallDir,
    [string]$ProjectName,
    [string]$StateDir,
    [string]$WorkingDirectory,
    [string]$ResumeSession,
    [string]$ExtraCopilotArgs,
    [switch]$EnableAISummary,
    [switch]$EnableAllowAll,
    [switch]$UseWindowsTerminal,
    [switch]$NoWindowsTerminal,
    [switch]$NoDesktopShortcut,
    [switch]$Silent
)

try {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $OutputEncoding           = [System.Text.Encoding]::UTF8
} catch {}

# ============================================================================
# EMBEDDED PAYLOADS (base64-encoded UTF-8). Replaced by build-installer.ps1.
# ============================================================================

$PAYLOAD_LAUNCH_COPILOT_PS1     = '{{LAUNCH_COPILOT_PS1_B64}}'
$PAYLOAD_NEW_COPILOT_SHORTCUT_PS1 = '{{NEW_COPILOT_SHORTCUT_PS1_B64}}'
$PAYLOAD_REPAIR_SESSIONS_PY     = '{{REPAIR_SESSIONS_PY_B64}}'
$PAYLOAD_AGENTS_EXAMPLE_MD      = '{{AGENTS_EXAMPLE_MD_B64}}'
$PAYLOAD_CONFIG_EXAMPLE_JSON    = '{{CONFIG_EXAMPLE_JSON_B64}}'
$PAYLOAD_README_MD              = '{{README_MD_B64}}'

function Decode-Payload {
    param([string]$Base64)
    # Detect un-substituted template placeholders (would start with {{ and end
    # with }}). We can't compare to a literal placeholder string here because
    # the build script replaces ALL occurrences of the placeholder pattern,
    # including the one inside this function.
    if (-not $Base64 -or $Base64 -match '^\{\{[A-Z_0-9]+\}\}$') {
        throw "Installer payload not populated. Re-run build-installer.ps1 to bundle source files."
    }
    return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Base64))
}

# ============================================================================
# Wizard helpers
# ============================================================================

function Read-Default {
    param(
        [string]$Prompt,
        [string]$Default,
        [string[]]$Description,
        [switch]$AllowEmpty
    )
    if ($script:SilentMode) {
        return $Default
    }
    if ($Description) {
        Write-Host ''
        foreach ($line in $Description) {
            Write-Host "  $line" -ForegroundColor DarkGray
        }
    }
    $shown = if ($Default) { "[$Default]" } else { '' }
    $resp = Read-Host "$Prompt $shown"
    if ([string]::IsNullOrWhiteSpace($resp)) {
        if (-not $AllowEmpty -and -not $Default) {
            Write-Host "  Value required." -ForegroundColor Yellow
            return Read-Default -Prompt $Prompt -Default $Default -Description $Description -AllowEmpty:$AllowEmpty
        }
        return $Default
    }
    return $resp.Trim()
}

function Read-YesNo {
    param(
        [string]$Prompt,
        [bool]$Default,
        [string[]]$Description
    )
    if ($script:SilentMode) { return $Default }
    if ($Description) {
        Write-Host ''
        foreach ($line in $Description) {
            Write-Host "  $line" -ForegroundColor DarkGray
        }
    }
    $hint = if ($Default) { '[Y/n]' } else { '[y/N]' }
    $resp = Read-Host "$Prompt $hint"
    if ([string]::IsNullOrWhiteSpace($resp)) { return $Default }
    return $resp.Trim().ToLower() -in @('y', 'yes', 'true', '1')
}

function Write-File {
    param(
        [string]$Path,
        [string]$Content,
        [switch]$PreserveExisting
    )
    $dir = Split-Path $Path -Parent
    if (-not (Test-Path $dir)) {
        $null = New-Item -ItemType Directory -Force -Path $dir
    }
    # Skip writing user-customized files (config.json, agents.md) if they
    # already exist, so re-running the installer to pick up new kit files
    # doesn't clobber the user's edits. Kit files (Launch-Copilot.ps1 etc.)
    # always overwrite because they are the kit, not user content.
    if ($PreserveExisting -and (Test-Path $Path)) {
        Write-Host "  Kept (existing)  $Path" -ForegroundColor DarkGray
        return
    }
    # Write .ps1 files with a UTF-8 BOM so Windows PowerShell 5.1 (which the
    # generated shortcut may fall back to when pwsh is not installed) decodes
    # non-ASCII characters in user-visible Write-Host strings correctly. PS 7
    # and the BOM-aware text editors handle it transparently. Other file types
    # (.py, .md, .json) stay no-BOM to avoid tripping parsers that don't
    # special-case the BOM.
    if ($Path -like '*.ps1') {
        $encoding = [System.Text.UTF8Encoding]::new($true)
    } else {
        $encoding = [System.Text.UTF8Encoding]::new($false)
    }
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
    Write-Host "  Wrote $Path" -ForegroundColor DarkGray
}

function Format-ShortcutArgs {
    # Build the Arguments string for a Windows .lnk so each individual arg
    # survives Windows command-line re-parsing. Wraps any value containing
    # whitespace or double-quotes in double-quotes; embedded quotes are
    # escaped by doubling. Anything safe is passed through unwrapped.
    # NOTE: parameter is named -Arguments (not -Args). $Args is a PowerShell
    # automatic variable and binding to it silently fails — produces empty
    # output with no error. Don't rename without re-testing the .lnk Arguments.
    param([string[]]$Arguments)
    $out = New-Object System.Collections.Generic.List[string]
    foreach ($a in $Arguments) {
        if ([string]::IsNullOrEmpty($a)) { continue }
        if ($a -match '[\s"]') {
            $escaped = $a -replace '"', '""'
            $out.Add('"' + $escaped + '"')
        } else {
            $out.Add($a)
        }
    }
    return ($out -join ' ')
}

function Split-CommandLine {
    # Tokenize a Windows-style command-line fragment, preserving double-quoted
    # spans as a single token. Used for -ExtraCopilotArgs so users can pass
    # things like '--max-autopilot-continues 100' or '--prompt "do the thing"'
    # and have the words re-quoted correctly by Format-ShortcutArgs.
    param([string]$Line)
    $out = New-Object System.Collections.Generic.List[string]
    if ([string]::IsNullOrWhiteSpace($Line)) { return ,$out.ToArray() }
    foreach ($m in [regex]::Matches($Line, '"([^"]*)"|(\S+)')) {
        if ($m.Groups[1].Success) {
            $out.Add($m.Groups[1].Value)
        } else {
            $out.Add($m.Groups[2].Value)
        }
    }
    return ,$out.ToArray()
}

function Find-WindowsTerminal {
    # Locate wt.exe. Returns full path or $null.
    $cmd = Get-Command wt.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

# ============================================================================
# Wizard
# ============================================================================

$script:SilentMode = [bool]$Silent

Write-Host ''
Write-Host '====================================================================' -ForegroundColor Cyan
Write-Host '   GitHub Copilot CLI Launcher — Installer' -ForegroundColor Cyan
Write-Host '====================================================================' -ForegroundColor Cyan
Write-Host ''
Write-Host 'This installer extracts a portable launcher kit, customizes it for your' -ForegroundColor Gray
Write-Host 'project, and creates a Windows shortcut you can use to launch Copilot CLI.' -ForegroundColor Gray
Write-Host ''
Write-Host 'Press Enter to accept the [default] for any prompt.' -ForegroundColor DarkGray
Write-Host ''

# ---------- Install location ----------
if (-not $InstallDir) {
    $InstallDir = Read-Default -Prompt 'Install location' `
        -Default (Join-Path $env:USERPROFILE 'copilot-launcher') `
        -Description @(
            'Where the launcher KIT files get extracted (Launch-Copilot.ps1, helpers,',
            'your config.json, agents.md). This is the launcher itself, not your project',
            'code and not where briefing logs go. Pick a folder you can leave alone.'
        )
}
$InstallDir = [Environment]::ExpandEnvironmentVariables($InstallDir)

# ---------- Project name ----------
if (-not $ProjectName) {
    $cwdName = Split-Path -Leaf (Get-Location).Path
    $ProjectName = Read-Default -Prompt 'Project name' -Default $cwdName `
        -Description @(
            'A short label for THIS launcher setup (not a folder path). It becomes:',
            '  - the desktop shortcut filename: "<name> Copilot.lnk"',
            '  - the briefing-session name passed to Copilot: "<name>-Briefings"',
            '  - the default subfolder name under the state directory',
            '  - substituted into agents.md wherever {ProjectName} appears',
            'Use letters/numbers/dashes. Example: "MyApp", "ClientX-Web", "scratch".'
        )
}

# ---------- State dir ----------
if (-not $StateDir) {
    $defaultStateDir = Join-Path ([Environment]::GetFolderPath('Desktop')) "CopilotCLI\$ProjectName"
    $StateDir = Read-Default -Prompt 'State directory' -Default $defaultStateDir `
        -Description @(
            'Where the launcher writes its long-lived state across launches:',
            '  - changelog briefings shown when Copilot CLI updates',
            '  - the recorded "last seen" version number',
            '  - cached AI-authored summaries and GitHub issue-status checks',
            'Often placed on Desktop or OneDrive so the briefing logs are visible.'
        )
}
$StateDir = [Environment]::ExpandEnvironmentVariables($StateDir)

# ---------- Working directory ----------
# Default to the directory the installer was launched from, NOT the install
# dir. The shortcut's working directory determines where Copilot starts; for
# project-specific shortcuts that should be the project root, not the kit
# folder. (Earlier versions defaulted to install dir, which was a latent bug
# for any user actually using Copilot against a project.)
if (-not $WorkingDirectory) {
    $WorkingDirectory = Read-Default -Prompt 'Shortcut working directory' `
        -Default ((Get-Location).Path) `
        -Description @(
            'Where Copilot will START when you double-click the shortcut.',
            'Usually your project root (e.g. C:\code\my-app), so Copilot can see',
            'your project files and your AGENTS.md.',
            'NOT the launcher install dir (that would mean Copilot opens with',
            'the kit folder as its working directory, which is rarely useful).',
            'Default = the folder you ran the installer from.'
        )
}
$WorkingDirectory = [Environment]::ExpandEnvironmentVariables($WorkingDirectory)
if (-not (Test-Path $WorkingDirectory)) {
    Write-Host "  ! Working directory does not exist: $WorkingDirectory" -ForegroundColor Yellow
    Write-Host "    The shortcut will still be created, but launching it will fail." -ForegroundColor Yellow
    Write-Host "    Create the folder before launching, or re-run with -WorkingDirectory <path>." -ForegroundColor Yellow
}

# ---------- Resume session ----------
# Use ContainsKey rather than `-not $ResumeSession` because an empty string is
# a valid explicit value (meaning "no resume session"). PowerShell binds an
# unspecified [string] param to '' (not $null), so we have to check whether
# the caller actually passed -ResumeSession to distinguish "not specified
# (prompt for it)" from "explicitly blank (skip the prompt)".
if (-not $PSBoundParameters.ContainsKey('ResumeSession')) {
    $ResumeSession = Read-Default -Prompt 'Default Copilot CLI --resume session name' `
        -Default '' -AllowEmpty `
        -Description @(
            'Optional. If you set a name here, every shortcut launch passes',
            '"--resume <name>" to copilot, so you keep ONE persistent conversation',
            'across launches (history, context, etc. are preserved).',
            'Leave blank to start a fresh Copilot session each launch.',
            'NOTE: this is the Copilot CLI session name, NOT the project name above.',
            'Example: "MyApp-Main", "ClientX-bugfix-2026-05".'
        )
}

# ---------- AI summary ----------
if (-not $PSBoundParameters.ContainsKey('EnableAISummary')) {
    $EnableAISummary = Read-YesNo -Prompt 'Enable AI-authored briefing summary?' -Default $false `
        -Description @(
            'When the Copilot CLI version changes, the launcher can ask an AI model',
            'to summarize the upstream changelog, tailored to your agents.md context.',
            'Each summary costs ONE premium model request, only on a version bump.',
            'Skip this for a plain "version bumped from X to Y, see release notes" notice.'
        )
}

# ---------- Allow-all ----------
if (-not $PSBoundParameters.ContainsKey('EnableAllowAll')) {
    $EnableAllowAll = Read-YesNo -Prompt 'Pass --allow-all to copilot?' -Default $false `
        -Description @(
            'Adds --allow-all so Copilot auto-approves every tool call without asking.',
            'Faster workflow, but bypasses the per-call safety prompt that lets you',
            'review what Copilot is about to do (run commands, edit files, etc.).',
            'Recommended only for scratch / dev environments you trust.'
        )
}

# ---------- Extra Copilot args ----------
if (-not $PSBoundParameters.ContainsKey('ExtraCopilotArgs')) {
    $ExtraCopilotArgs = Read-Default -Prompt 'Extra copilot CLI args' -Default '' -AllowEmpty `
        -Description @(
            'Optional. Extra arguments appended to the copilot command line in',
            'the shortcut. Useful for flags this wizard does not have a dedicated',
            'prompt for, such as:',
            '    --max-autopilot-continues 100',
            '    --max-autopilot-continues 100 --some-other-flag value',
            'Leave blank for none. Quoted values are preserved as single args:',
            '    --prompt "do the thing"'
        )
}

# ---------- Windows Terminal ----------
$wtPath = Find-WindowsTerminal
if ($PSBoundParameters.ContainsKey('NoWindowsTerminal')) {
    $UseWindowsTerminal = -not [bool]$NoWindowsTerminal
} elseif ($PSBoundParameters.ContainsKey('UseWindowsTerminal')) {
    # Already bound
} else {
    $defaultWT = [bool]$wtPath
    $UseWindowsTerminal = Read-YesNo -Prompt 'Launch via Windows Terminal (wt.exe)?' -Default $defaultWT `
        -Description @(
            'When enabled, the shortcut targets wt.exe instead of pwsh.exe and',
            'opens Copilot in a new Windows Terminal tab/window. Equivalent to:',
            '    wt.exe -w 0 -d "<workdir>" "<pwsh>" -NoExit -File "<launcher>" ...',
            'Benefits: tab support, profile theming, and your default WT settings.',
            "Default = $(if ($defaultWT) { 'yes (wt.exe found on PATH)' } else { 'no (wt.exe not found)' })."
        )
}
if ($UseWindowsTerminal -and -not $wtPath) {
    Write-Host '  ! Windows Terminal selected but wt.exe not on PATH; falling back to pwsh.exe target.' -ForegroundColor Yellow
    $UseWindowsTerminal = $false
}

# ---------- Shortcut ----------
$CreateDesktopShortcut = $true
if ($PSBoundParameters.ContainsKey('NoDesktopShortcut')) {
    $CreateDesktopShortcut = -not [bool]$NoDesktopShortcut
} elseif (-not $script:SilentMode) {
    $CreateDesktopShortcut = Read-YesNo -Prompt 'Create desktop shortcut?' -Default $true `
        -Description @(
            'Creates a Windows shortcut on your Desktop named "<Project name> Copilot.lnk"',
            'that launches the wrapper with the options you chose above.'
        )
}

$briefingSessionName = "$ProjectName-Briefings"

Write-Host ''
Write-Host 'Summary:' -ForegroundColor Cyan
Write-Host "  Install location:       $InstallDir"
Write-Host "  Project name:           $ProjectName"
Write-Host "  State directory:        $StateDir"
Write-Host "  Shortcut working dir:   $WorkingDirectory"
Write-Host "  Briefing session name:  $briefingSessionName"
Write-Host "  Resume session:         $(if ($ResumeSession) { $ResumeSession } else { '(none — fresh session each launch)' })"
Write-Host "  AI summary:             $(if ($EnableAISummary) { 'enabled' } else { 'disabled' })"
Write-Host "  --allow-all:            $(if ($EnableAllowAll) { 'enabled' } else { 'disabled' })"
Write-Host "  Extra copilot args:     $(if ($ExtraCopilotArgs) { $ExtraCopilotArgs } else { '(none)' })"
Write-Host "  Launch via Win Terminal: $(if ($UseWindowsTerminal) { 'yes' } else { 'no (pwsh direct)' })"
Write-Host "  Desktop shortcut:       $(if ($CreateDesktopShortcut) { 'yes' } else { 'no' })"
Write-Host ''

if (-not $script:SilentMode) {
    $confirm = Read-Host 'Proceed with installation? [Y/n]'
    if ($confirm.Trim().ToLower() -in @('n', 'no')) {
        Write-Host 'Cancelled.' -ForegroundColor Yellow
        exit 0
    }
}

# ============================================================================
# Install
# ============================================================================

Write-Host ''
Write-Host 'Installing...' -ForegroundColor Cyan

$null = New-Item -ItemType Directory -Force -Path $InstallDir
$null = New-Item -ItemType Directory -Force -Path $StateDir

# Decode and write source files
Write-File -Path (Join-Path $InstallDir 'Launch-Copilot.ps1')           -Content (Decode-Payload $PAYLOAD_LAUNCH_COPILOT_PS1)
Write-File -Path (Join-Path $InstallDir 'New-CopilotShortcut.ps1')      -Content (Decode-Payload $PAYLOAD_NEW_COPILOT_SHORTCUT_PS1)
Write-File -Path (Join-Path $InstallDir 'repair-copilot-sessions.py')   -Content (Decode-Payload $PAYLOAD_REPAIR_SESSIONS_PY)
Write-File -Path (Join-Path $InstallDir 'README.md')                    -Content (Decode-Payload $PAYLOAD_README_MD)
Write-File -Path (Join-Path $InstallDir 'config.example.json')          -Content (Decode-Payload $PAYLOAD_CONFIG_EXAMPLE_JSON)
Write-File -Path (Join-Path $InstallDir 'agents.example.md')            -Content (Decode-Payload $PAYLOAD_AGENTS_EXAMPLE_MD)

# Generate user config from wizard inputs
$userConfig = [ordered]@{
    projectName            = $ProjectName
    stateDir               = $StateDir
    agentsMdPath           = './agents.md'
    briefingSessionName    = $briefingSessionName
    trackedIssues          = @(3298)
    applyKnownWorkarounds  = $true
    autoUpdate             = $true
}
$configJson = $userConfig | ConvertTo-Json -Depth 4
Write-File -Path (Join-Path $InstallDir 'config.json') -Content $configJson -PreserveExisting

# Generate user AGENTS.md from template (with project name substituted)
$agentsContent = (Decode-Payload $PAYLOAD_AGENTS_EXAMPLE_MD).Replace('{ProjectName}', $ProjectName)
Write-File -Path (Join-Path $InstallDir 'agents.md') -Content $agentsContent -PreserveExisting

# ---------- Shortcut ----------
if ($CreateDesktopShortcut) {
    Write-Host ''
    Write-Host 'Creating desktop shortcut...' -ForegroundColor Cyan

    $launcherPath = Join-Path $InstallDir 'Launch-Copilot.ps1'
    $shortcutName = "$ProjectName Copilot.lnk"
    $shortcutPath = Join-Path ([Environment]::GetFolderPath('Desktop')) $shortcutName

    # Find pwsh.exe (prefer PowerShell 7+) or fall back to powershell.exe
    $pwshCmd = Get-Command pwsh.exe -ErrorAction SilentlyContinue
    if (-not $pwshCmd) {
        $pwshCmd = Get-Command powershell.exe -ErrorAction SilentlyContinue
    }
    if (-not $pwshCmd) {
        Write-Host '  ! Could not find pwsh.exe or powershell.exe — skipping shortcut.' -ForegroundColor Yellow
    } else {
        # Inner pwsh + launcher args (always built; either consumed directly
        # as the shortcut Arguments, or as the tail end of a wt.exe argline).
        $pwshLauncherArgs = @(
            '-NoExit',
            '-NoLogo',
            '-ExecutionPolicy', 'Bypass',
            '-File', $launcherPath
        )
        if ($EnableAISummary)  { $pwshLauncherArgs += '-AISummary' }
        if ($EnableAllowAll)   { $pwshLauncherArgs += '--allow-all' }
        if ($ResumeSession)    { $pwshLauncherArgs += "--resume=$ResumeSession" }
        if ($ExtraCopilotArgs) { $pwshLauncherArgs += (Split-CommandLine $ExtraCopilotArgs) }

        if ($UseWindowsTerminal -and $wtPath) {
            # wt.exe -w 0 -d "<workdir>" "<pwsh>" <pwsh args>
            $targetExe = $wtPath
            $argList = @('-w', '0', '-d', $WorkingDirectory, $pwshCmd.Source) + $pwshLauncherArgs
        } else {
            $targetExe = $pwshCmd.Source
            $argList = $pwshLauncherArgs
        }

        try {
            $shell = New-Object -ComObject WScript.Shell
            $sc = $shell.CreateShortcut($shortcutPath)
            $sc.TargetPath       = $targetExe
            $sc.Arguments        = Format-ShortcutArgs -Arguments $argList
            $sc.WorkingDirectory = $WorkingDirectory
            $sc.Description      = "Launch GitHub Copilot CLI for $ProjectName with version-change briefing"
            # Use the pwsh icon (WT inherits its own icon from the .lnk if we
            # pointed at wt.exe, but pwsh's icon is more recognisable)
            $sc.IconLocation     = $pwshCmd.Source
            $sc.Save()
            Write-Host "  Created shortcut: $shortcutPath" -ForegroundColor Green
        } catch {
            Write-Host "  ! Failed to create shortcut: $_" -ForegroundColor Yellow
        }
    }
}

# ============================================================================
# Done
# ============================================================================

Write-Host ''
Write-Host '====================================================================' -ForegroundColor Green
Write-Host '   Installation complete' -ForegroundColor Green
Write-Host '====================================================================' -ForegroundColor Green
Write-Host ''
Write-Host "Kit installed to:    $InstallDir" -ForegroundColor Gray
Write-Host "Briefings + state:   $StateDir" -ForegroundColor Gray
if ($CreateDesktopShortcut) {
    Write-Host "Shortcut:            $($shortcutPath)" -ForegroundColor Gray
}
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host "  1. Edit  $InstallDir\agents.md  to describe your project for the AI summary" -ForegroundColor Gray
if ($CreateDesktopShortcut) {
    Write-Host '  2. Double-click the desktop shortcut to launch.' -ForegroundColor Gray
} else {
    Write-Host "  2. Run:  pwsh -File `"$InstallDir\Launch-Copilot.ps1`"" -ForegroundColor Gray
}
Write-Host '  3. First launch records the current Copilot CLI version with no briefing.' -ForegroundColor Gray
Write-Host '     From the next launch onward, you will see a changelog briefing on each' -ForegroundColor Gray
Write-Host "     launch where the version has advanced." -ForegroundColor Gray
Write-Host '  4. To create more shortcuts later (different projects, different sessions):' -ForegroundColor Gray
Write-Host "       cd <your project>" -ForegroundColor Gray
Write-Host "       pwsh `"$InstallDir\New-CopilotShortcut.ps1`"" -ForegroundColor Gray
Write-Host ''
Write-Host "Read more in $InstallDir\README.md" -ForegroundColor DarkGray
Write-Host ''
