<#
.SYNOPSIS
    One-file installer for the GitHub Copilot CLI Launcher kit.
    Wizard mode (default): prompts for project name, install location, etc.,
    writes all kit files, and creates a Windows desktop shortcut.
    Silent mode: pass parameters to skip prompts.

.DESCRIPTION
    This is a self-contained installer. It embeds the entire kit
    (Launch-Copilot.ps1, repair-copilot-sessions.py, AGENTS.md template,
    config schema) as base64-encoded payloads. No external downloads or
    git clone required.

    Generated by: tools/copilot-launcher/build-installer.ps1
    Source repo:  {{REPO_URL}}
    Build date:   {{BUILD_DATE}}

.PARAMETER InstallDir
    Where to install the kit. Default: %USERPROFILE%\copilot-launcher

.PARAMETER ProjectName
    Used in messages and as the default briefing-session name.
    Default: prompted (or current dir name in silent mode).

.PARAMETER StateDir
    Where briefing logs and state files live.
    Default: %USERPROFILE%\Desktop\CopilotCLI\<ProjectName>

.PARAMETER ResumeSession
    Copilot CLI session name to --resume on launch (e.g. "MyProject-Main").
    Leave empty to start a fresh session each launch. Default: empty.

.PARAMETER EnableAISummary
    Add -AISummary to the shortcut. Costs one premium request per launch
    when an update is detected. Default: prompted.

.PARAMETER EnableAllowAll
    Add --allow-all to the shortcut (Copilot CLI auto-approve mode).
    Default: prompted.

.PARAMETER NoDesktopShortcut
    Skip creating the desktop shortcut. Default: shortcut is created
    (after a wizard confirmation prompt).

.PARAMETER Silent
    Skip all prompts and use parameter values + defaults.

.EXAMPLE
    # Interactive wizard
    .\Install-CopilotLauncher.ps1

.EXAMPLE
    # Silent install with defaults
    .\Install-CopilotLauncher.ps1 -Silent -ProjectName "MyApp" -ResumeSession "MyApp-Main" -EnableAISummary -EnableAllowAll

.EXAMPLE
    # Custom install dir, no shortcut
    .\Install-CopilotLauncher.ps1 -InstallDir "D:\tools\copilot-launcher" -NoDesktopShortcut
#>
[CmdletBinding()]
param(
    [string]$InstallDir,
    [string]$ProjectName,
    [string]$StateDir,
    [string]$ResumeSession,
    [switch]$EnableAISummary,
    [switch]$EnableAllowAll,
    [switch]$NoDesktopShortcut,
    [switch]$Silent
)

try {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $OutputEncoding           = [System.Text.Encoding]::UTF8
} catch {}

# ============================================================================
# EMBEDDED PAYLOADS (base64-encoded UTF-8). Replaced by build-installer.ps1.
# ============================================================================

$PAYLOAD_LAUNCH_COPILOT_PS1     = '{{LAUNCH_COPILOT_PS1_B64}}'
$PAYLOAD_REPAIR_SESSIONS_PY     = '{{REPAIR_SESSIONS_PY_B64}}'
$PAYLOAD_AGENTS_EXAMPLE_MD      = '{{AGENTS_EXAMPLE_MD_B64}}'
$PAYLOAD_CONFIG_EXAMPLE_JSON    = '{{CONFIG_EXAMPLE_JSON_B64}}'
$PAYLOAD_README_MD              = '{{README_MD_B64}}'

function Decode-Payload {
    param([string]$Base64)
    # Detect un-substituted template placeholders (would start with {{ and end
    # with }}). We can't compare to a literal placeholder string here because
    # the build script replaces ALL occurrences of the placeholder pattern,
    # including the one inside this function.
    if (-not $Base64 -or $Base64 -match '^\{\{[A-Z_0-9]+\}\}$') {
        throw "Installer payload not populated. Re-run build-installer.ps1 to bundle source files."
    }
    return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Base64))
}

# ============================================================================
# Wizard helpers
# ============================================================================

function Read-Default {
    param(
        [string]$Prompt,
        [string]$Default,
        [switch]$AllowEmpty
    )
    if ($script:SilentMode) {
        return $Default
    }
    $shown = if ($Default) { "[$Default]" } else { '' }
    $resp = Read-Host "$Prompt $shown"
    if ([string]::IsNullOrWhiteSpace($resp)) {
        if (-not $AllowEmpty -and -not $Default) {
            Write-Host "  Value required." -ForegroundColor Yellow
            return Read-Default -Prompt $Prompt -Default $Default -AllowEmpty:$AllowEmpty
        }
        return $Default
    }
    return $resp.Trim()
}

function Read-YesNo {
    param([string]$Prompt, [bool]$Default)
    if ($script:SilentMode) { return $Default }
    $hint = if ($Default) { '[Y/n]' } else { '[y/N]' }
    $resp = Read-Host "$Prompt $hint"
    if ([string]::IsNullOrWhiteSpace($resp)) { return $Default }
    return $resp.Trim().ToLower() -in @('y', 'yes', 'true', '1')
}

function Write-File {
    param([string]$Path, [string]$Content)
    $dir = Split-Path $Path -Parent
    if (-not (Test-Path $dir)) {
        $null = New-Item -ItemType Directory -Force -Path $dir
    }
    # Use UTF-8 without BOM to match how the source files are stored
    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
    Write-Host "  Wrote $Path" -ForegroundColor DarkGray
}

# ============================================================================
# Wizard
# ============================================================================

$script:SilentMode = [bool]$Silent

Write-Host ''
Write-Host '====================================================================' -ForegroundColor Cyan
Write-Host '   GitHub Copilot CLI Launcher — Installer' -ForegroundColor Cyan
Write-Host '====================================================================' -ForegroundColor Cyan
Write-Host ''
Write-Host 'This installer extracts a portable launcher kit, customizes it for your' -ForegroundColor Gray
Write-Host 'project, and creates a Windows shortcut you can use to launch Copilot CLI.' -ForegroundColor Gray
Write-Host ''
Write-Host 'Press Enter to accept the [default] for any prompt.' -ForegroundColor DarkGray
Write-Host ''

# ---------- Install location ----------
if (-not $InstallDir) {
    $InstallDir = Read-Default -Prompt 'Install location' -Default (Join-Path $env:USERPROFILE 'copilot-launcher')
}
$InstallDir = [Environment]::ExpandEnvironmentVariables($InstallDir)

# ---------- Project name ----------
if (-not $ProjectName) {
    $cwdName = Split-Path -Leaf (Get-Location).Path
    $ProjectName = Read-Default -Prompt 'Project name' -Default $cwdName
}

# ---------- State dir ----------
if (-not $StateDir) {
    $defaultStateDir = Join-Path ([Environment]::GetFolderPath('Desktop')) "CopilotCLI\$ProjectName"
    $StateDir = Read-Default -Prompt 'State directory (briefing logs, history)' -Default $defaultStateDir
}
$StateDir = [Environment]::ExpandEnvironmentVariables($StateDir)

# ---------- Resume session ----------
# Use ContainsKey rather than `-not $ResumeSession` because an empty string is
# a valid explicit value (meaning "no resume session"). PowerShell binds an
# unspecified [string] param to '' (not $null), so we have to check whether
# the caller actually passed -ResumeSession to distinguish "not specified
# (prompt for it)" from "explicitly blank (skip the prompt)".
if (-not $PSBoundParameters.ContainsKey('ResumeSession')) {
    $ResumeSession = Read-Default -Prompt 'Default Copilot CLI --resume session (blank = none)' -Default '' -AllowEmpty
}

# ---------- AI summary ----------
if (-not $PSBoundParameters.ContainsKey('EnableAISummary')) {
    $EnableAISummary = Read-YesNo -Prompt 'Enable AI-authored briefing summary? (uses one premium request per update)' -Default $false
}

# ---------- Allow-all ----------
if (-not $PSBoundParameters.ContainsKey('EnableAllowAll')) {
    $EnableAllowAll = Read-YesNo -Prompt 'Pass --allow-all to copilot? (auto-approves tool calls)' -Default $false
}

# ---------- Shortcut ----------
$CreateDesktopShortcut = $true
if ($PSBoundParameters.ContainsKey('NoDesktopShortcut')) {
    $CreateDesktopShortcut = -not [bool]$NoDesktopShortcut
} elseif (-not $script:SilentMode) {
    $CreateDesktopShortcut = Read-YesNo -Prompt 'Create desktop shortcut?' -Default $true
}

$briefingSessionName = "$ProjectName-Briefings"

Write-Host ''
Write-Host 'Summary:' -ForegroundColor Cyan
Write-Host "  Install location:       $InstallDir"
Write-Host "  Project name:           $ProjectName"
Write-Host "  State directory:        $StateDir"
Write-Host "  Briefing session name:  $briefingSessionName"
Write-Host "  Resume session:         $(if ($ResumeSession) { $ResumeSession } else { '(none — fresh session each launch)' })"
Write-Host "  AI summary:             $(if ($EnableAISummary) { 'enabled' } else { 'disabled' })"
Write-Host "  --allow-all:            $(if ($EnableAllowAll) { 'enabled' } else { 'disabled' })"
Write-Host "  Desktop shortcut:       $(if ($CreateDesktopShortcut) { 'yes' } else { 'no' })"
Write-Host ''

if (-not $script:SilentMode) {
    $confirm = Read-Host 'Proceed with installation? [Y/n]'
    if ($confirm.Trim().ToLower() -in @('n', 'no')) {
        Write-Host 'Cancelled.' -ForegroundColor Yellow
        exit 0
    }
}

# ============================================================================
# Install
# ============================================================================

Write-Host ''
Write-Host 'Installing...' -ForegroundColor Cyan

$null = New-Item -ItemType Directory -Force -Path $InstallDir
$null = New-Item -ItemType Directory -Force -Path $StateDir

# Decode and write source files
Write-File -Path (Join-Path $InstallDir 'Launch-Copilot.ps1')           -Content (Decode-Payload $PAYLOAD_LAUNCH_COPILOT_PS1)
Write-File -Path (Join-Path $InstallDir 'repair-copilot-sessions.py')   -Content (Decode-Payload $PAYLOAD_REPAIR_SESSIONS_PY)
Write-File -Path (Join-Path $InstallDir 'README.md')                    -Content (Decode-Payload $PAYLOAD_README_MD)
Write-File -Path (Join-Path $InstallDir 'config.example.json')          -Content (Decode-Payload $PAYLOAD_CONFIG_EXAMPLE_JSON)
Write-File -Path (Join-Path $InstallDir 'agents.example.md')            -Content (Decode-Payload $PAYLOAD_AGENTS_EXAMPLE_MD)

# Generate user config from wizard inputs
$userConfig = [ordered]@{
    projectName            = $ProjectName
    stateDir               = $StateDir
    agentsMdPath           = './agents.md'
    briefingSessionName    = $briefingSessionName
    trackedIssues          = @(3298)
    applyKnownWorkarounds  = $true
    autoUpdate             = $true
}
$configJson = $userConfig | ConvertTo-Json -Depth 4
Write-File -Path (Join-Path $InstallDir 'config.json') -Content $configJson

# Generate user AGENTS.md from template (with project name substituted)
$agentsContent = (Decode-Payload $PAYLOAD_AGENTS_EXAMPLE_MD).Replace('{ProjectName}', $ProjectName)
Write-File -Path (Join-Path $InstallDir 'agents.md') -Content $agentsContent

# ---------- Shortcut ----------
if ($CreateDesktopShortcut) {
    Write-Host ''
    Write-Host 'Creating desktop shortcut...' -ForegroundColor Cyan

    $launcherPath = Join-Path $InstallDir 'Launch-Copilot.ps1'
    $shortcutName = "$ProjectName Copilot.lnk"
    $shortcutPath = Join-Path ([Environment]::GetFolderPath('Desktop')) $shortcutName

    # Find pwsh.exe (prefer PowerShell 7+) or fall back to powershell.exe
    $pwshCmd = Get-Command pwsh.exe -ErrorAction SilentlyContinue
    if (-not $pwshCmd) {
        $pwshCmd = Get-Command powershell.exe -ErrorAction SilentlyContinue
    }
    if (-not $pwshCmd) {
        Write-Host '  ! Could not find pwsh.exe or powershell.exe — skipping shortcut.' -ForegroundColor Yellow
    } else {
        $argList = @(
            '-NoExit',
            '-NoLogo',
            '-ExecutionPolicy', 'Bypass',
            '-File', "`"$launcherPath`""
        )
        if ($EnableAISummary) { $argList += '-AISummary' }
        if ($ResumeSession)   { $argList += "--resume=$ResumeSession" }
        if ($EnableAllowAll)  { $argList += '--allow-all' }

        try {
            $shell = New-Object -ComObject WScript.Shell
            $sc = $shell.CreateShortcut($shortcutPath)
            $sc.TargetPath       = $pwshCmd.Source
            $sc.Arguments        = ($argList -join ' ')
            $sc.WorkingDirectory = $InstallDir
            $sc.Description      = "Launch GitHub Copilot CLI for $ProjectName with version-change briefing"
            # Use the Windows Terminal icon if available, else the pwsh icon
            $sc.IconLocation     = $pwshCmd.Source
            $sc.Save()
            Write-Host "  Created shortcut: $shortcutPath" -ForegroundColor Green
        } catch {
            Write-Host "  ! Failed to create shortcut: $_" -ForegroundColor Yellow
        }
    }
}

# ============================================================================
# Done
# ============================================================================

Write-Host ''
Write-Host '====================================================================' -ForegroundColor Green
Write-Host '   Installation complete' -ForegroundColor Green
Write-Host '====================================================================' -ForegroundColor Green
Write-Host ''
Write-Host "Kit installed to:    $InstallDir" -ForegroundColor Gray
Write-Host "Briefings + state:   $StateDir" -ForegroundColor Gray
if ($CreateDesktopShortcut) {
    Write-Host "Shortcut:            $($shortcutPath)" -ForegroundColor Gray
}
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host "  1. Edit  $InstallDir\agents.md  to describe your project for the AI summary" -ForegroundColor Gray
if ($CreateDesktopShortcut) {
    Write-Host '  2. Double-click the desktop shortcut to launch.' -ForegroundColor Gray
} else {
    Write-Host "  2. Run:  pwsh -File `"$InstallDir\Launch-Copilot.ps1`"" -ForegroundColor Gray
}
Write-Host '  3. First launch records the current Copilot CLI version with no briefing.' -ForegroundColor Gray
Write-Host '     From the next launch onward, you will see a changelog briefing on each' -ForegroundColor Gray
Write-Host "     launch where the version has advanced." -ForegroundColor Gray
Write-Host ''
Write-Host "Read more in $InstallDir\README.md" -ForegroundColor DarkGray
Write-Host ''
